version: "3"
networks:
 kong-net:
  driver: bridge
  ipam:
    config:
      - subnet: 172.18.0.0/16

services:
  #######################################
  # Postgres: The database used by Kong
  #######################################
  kong-database:
    image: postgres:9.6
    restart: always
    networks:
      kong-net:
        ipv4_address: 172.18.0.2
    environment:
      POSTGRES_USER: kong
      POSTGRES_DB: kong
      POSTGRES_PASSWORD: kong
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "kong"]
      interval: 5s
      timeout: 5s
      retries: 5

  #######################################
  # Kong database migration
  #######################################
  kong-migration:
    image: kong:latest
    command: "kong migrations bootstrap"
    networks:
      kong-net:
        ipv4_address: 172.18.0.3
    restart: on-failure
    environment:
      KONG_PG_HOST: kong-database
      KONG_PG_PASSWORD: kong
    links:
      - kong-database
    depends_on:
      - kong-database

  #######################################
  # Kong: The API Gateway
  #######################################
  kong:
    image: kong:latest
    restart: always
    networks:
      kong-net:
        ipv4_address: 172.18.0.4
    environment:
      KONG_PG_HOST: 172.18.0.2
      KONG_PG_PASSWORD: kong
      KONG_PROXY_LISTEN: 0.0.0.0:8000
      KONG_PROXY_LISTEN_SSL: 0.0.0.0:8443
      KONG_ADMIN_LISTEN: 0.0.0.0:8001
    depends_on:
      - kong-database
    healthcheck:
      test: ["CMD", "curl", "-f", "http://kong:8001"]
      interval: 5s
      timeout: 2s
      retries: 15
    ports:
      - 8001:8001
      - 8000:8000
      - 8443:8443
      - 8444:8444

  konga-prepare:
    image: pantsel/konga:latest
    command: "-c prepare -a postgres -u postgresql://kong:kong@kong-database:5432/konga"
    networks:
      kong-net:
        ipv4_address: 172.18.0.10
    restart: on-failure
    depends_on:
      - kong-database

  konga:
    image: pantsel/konga
    depends_on:
      - kong-database
    networks:
      kong-net:
        ipv4_address: 172.18.0.5
    ports:
      - 1337:1337
    restart: on-failure
    environment:
      TOKEN_SECRET: 4njasmara!
      DB_ADAPTER: postgres
      DB_HOST: kong-database
      DB_PORT: 5432
      DB_USER: konga
      DB_PASSWORD: 
      DB_DATABASE: konga
      DB_URI: postgresql://kong:kong@kong-database:5432/konga
      NODE_ENV: development
#      KONGA_HOOK_TIMEOUT: 10000

  mariadb:
    image: mariadb:10.4
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_DATABASE: kong
      MYSQL_ROOT_PASSWORD: anjas123
      MYSQL_USER: root
      MYSQL_PASSWORD: anjas123
    ports:
      - 3306:3306
    depends_on:
      - kong
    networks:
      kong-net:
        ipv4_address: 172.18.0.6
    volumes:
      - ~/docker/mariadb/dirdata:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin
    restart: always
    depends_on:
      - mariadb
    networks:
      kong-net:
        ipv4_address: 172.18.0.7
    links:
      - mariadb:mariadb
    ports:
      - 8888:80
    environment:
      PMA_ARBITRARY: 1
      PMA_HOST: mariadb
      MYSQL_USER: root
      MYSQL_PASSWORD: anjas123

  generals:
    build: ~/docker/anjasmara_service_general/
#    env_file:
#      - .env
    depends_on:
      - kong
      - mariadb
      - kong-database
    networks:
      kong-net:
        ipv4_address: 172.18.0.8
    links:
      - kong:kong
      - mariadb:mariadb
    ports:
      - 3001:3001
    environment:
      MYSQL_DATABASE: anjasmara_service_general
      MYSQL_USER: root
      MYSQL_PASSWORD: anjas123
  users:
    build : ~/docker/anjasmara_service_users_v1
    networks:
      kong-net:
        ipv4_address: 172.18.0.9
    depends_on:
      - kong
      - mariadb
      - kong-database
    links:
      - kong:kong
      - mariadb:mariadb
    ports:
      - 3000:3000
    environment:
       MYSQL_DATABASE: anjasmara_service_user
       MYSQL_USER: root
       MYSQL_PASSWORD:

